# Form implementation generated from reading ui file '/Users/yhtyyarannayev/Documents/GitHub/Python-Module-Week7/English/admin_menu.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet(
            "padding:0;\n" "background-image: url(./assets/zemin-buyuk.jpg);"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.interviews_Button = QtWidgets.QPushButton(self.centralwidget)
        self.interviews_Button.setGeometry(QtCore.QRect(320, 350, 141, 31))
        self.interviews_Button.setAutoFillBackground(False)
        self.interviews_Button.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.interviews_Button.setObjectName("interviews_Button")
        self.Mentor_interview_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Mentor_interview_Button.setGeometry(QtCore.QRect(520, 350, 181, 31))
        self.Mentor_interview_Button.setAutoFillBackground(False)
        self.Mentor_interview_Button.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.Mentor_interview_Button.setObjectName("Mentor_interview_Button")
        self.Admin_menu_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Admin_menu_Button.setGeometry(QtCore.QRect(440, 280, 141, 31))
        self.Admin_menu_Button.setAutoFillBackground(False)
        self.Admin_menu_Button.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.Admin_menu_Button.setObjectName("Admin_menu_Button")
        self.main_menu = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu.setGeometry(QtCore.QRect(220, 280, 141, 31))
        self.main_menu.setAutoFillBackground(False)
        self.main_menu.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.main_menu.setObjectName("main_menu")
        self.applications_Button = QtWidgets.QPushButton(self.centralwidget)
        self.applications_Button.setGeometry(QtCore.QRect(100, 350, 141, 31))
        self.applications_Button.setAutoFillBackground(False)
        self.applications_Button.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.applications_Button.setObjectName("applications_Button")
        self.exit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_Button.setGeometry(QtCore.QRect(610, 500, 91, 31))
        self.exit_Button.setAutoFillBackground(False)
        self.exit_Button.setStyleSheet(
            "QPushButton{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "\n"
            "QPushButton::hover{\n"
            "color:#47545a;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.exit_Button.setObjectName("exit_Button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 130, 221, 41))
        self.label_2.setStyleSheet(
            "color:white;\n" "font-size:36px;\n" "font-weight:bold;\n" "background:none"
        )
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.interviews_Button.setText(_translate("MainWindow", "INTERVIEWS"))
        self.Mentor_interview_Button.setText(
            _translate("MainWindow", "MENTOR INTERVIEW")
        )
        self.Admin_menu_Button.setText(_translate("MainWindow", "ADMIN MENU"))
        self.main_menu.setText(_translate("MainWindow", "MAIN MENU"))
        self.applications_Button.setText(_translate("MainWindow", "APPLICATIONS"))
        self.exit_Button.setText(_translate("MainWindow", "EXIT"))
        self.label_2.setText(_translate("MainWindow", "ADMIN MENU"))
