# Form implementation generated from reading ui file '/Users/yhtyyar/Documents/GitHub/Python-Module-Week7/application_menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("background-image: url(./assets/zemin-buyuk.jpg);\n"
"QWidget::setFixedSize(800, 600);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search.setGeometry(QtCore.QRect(680, 140, 100, 32))
        self.search.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#db1e3c;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#db1e3c;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.search.setObjectName("search")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 70, 241, 41))
        self.label.setStyleSheet("color:white;\n"
"font-size:36px;\n"
"font-weight:bold;\n"
"background:none")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 140, 361, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-radius:10px;\n"
"background:none;\n"
"padding:5px\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.assigned_mentor_interviews = QtWidgets.QPushButton(parent=self.centralwidget)
        self.assigned_mentor_interviews.setGeometry(QtCore.QRect(20, 180, 231, 32))
        self.assigned_mentor_interviews.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.assigned_mentor_interviews.setObjectName("assigned_mentor_interviews")
        self.unassigned_mentor_interviews = QtWidgets.QPushButton(parent=self.centralwidget)
        self.unassigned_mentor_interviews.setGeometry(QtCore.QRect(20, 220, 251, 32))
        self.unassigned_mentor_interviews.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.unassigned_mentor_interviews.setObjectName("unassigned_mentor_interviews")
        self.prev_vit_check = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prev_vit_check.setGeometry(QtCore.QRect(310, 180, 151, 32))
        self.prev_vit_check.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.prev_vit_check.setObjectName("prev_vit_check")
        self.filtered_applications = QtWidgets.QPushButton(parent=self.centralwidget)
        self.filtered_applications.setGeometry(QtCore.QRect(310, 220, 151, 32))
        self.filtered_applications.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.filtered_applications.setObjectName("filtered_applications")
        self.duplicate_application = QtWidgets.QPushButton(parent=self.centralwidget)
        self.duplicate_application.setGeometry(QtCore.QRect(470, 180, 151, 32))
        self.duplicate_application.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.duplicate_application.setObjectName("duplicate_application")
        self.different_registeration = QtWidgets.QPushButton(parent=self.centralwidget)
        self.different_registeration.setGeometry(QtCore.QRect(470, 220, 151, 32))
        self.different_registeration.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.different_registeration.setObjectName("different_registeration")
        self.all_applications = QtWidgets.QPushButton(parent=self.centralwidget)
        self.all_applications.setGeometry(QtCore.QRect(20, 140, 141, 31))
        self.all_applications.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.all_applications.setObjectName("all_applications")
        self.main_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.main_menu.setGeometry(QtCore.QRect(630, 180, 151, 32))
        self.main_menu.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.main_menu.setObjectName("main_menu")
        self.exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(630, 220, 151, 32))
        self.exit.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#47545a;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.exit.setObjectName("exit")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 270, 761, 321))
        self.tableWidget.setStyleSheet("QTableView{\n"
"color:black;\n"
"background:white;\n"
"font-weight:bold;\n"
"border-radius:5px\n"
"}")
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "APPLICATIONS"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your search term..."))
        self.assigned_mentor_interviews.setText(_translate("MainWindow", "Assigned Mentor Interviews"))
        self.unassigned_mentor_interviews.setText(_translate("MainWindow", "Unassigned Mentor Interviews"))
        self.prev_vit_check.setText(_translate("MainWindow", "Prev VIT Check"))
        self.filtered_applications.setText(_translate("MainWindow", "Filtered Application"))
        self.duplicate_application.setText(_translate("MainWindow", "Duplicate Application"))
        self.different_registeration.setText(_translate("MainWindow", "Differrent Registration"))
        self.all_applications.setText(_translate("MainWindow", "All Aplications"))
        self.main_menu.setText(_translate("MainWindow", "Main Menu"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Isim Soyisim"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telefon"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Posta Kodu"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Eyalet"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Mevcut Durum"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ekonomik Durum"))
