# Form implementation generated from reading ui file 'application-page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(
            "background-image: url(./assets/zemin-buyuk.jpg);\n"
            "QWidget::setFixedSize(800, 600);"
        )
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 140, 100, 32))
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "color:white;\n"
            "background:#db1e3c;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "\n"
            "QPushButton::hover{\n"
            "color:#db1e3c;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 70, 271, 41))
        self.label.setStyleSheet(
            "color:white;\n" "font-size:36px;\n" "font-weight:bold;\n" "background:none"
        )
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 140, 361, 31))
        self.lineEdit.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "background:none;\n"
            "padding:5px\n"
            "}"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 231, 32))
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 220, 251, 32))
        self.pushButton_3.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 180, 151, 32))
        self.pushButton_4.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 220, 151, 32))
        self.pushButton_5.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 180, 151, 32))
        self.pushButton_6.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 220, 151, 32))
        self.pushButton_7.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 140, 141, 31))
        self.pushButton_8.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(630, 180, 151, 32))
        self.pushButton_9.setStyleSheet(
            "QPushButton{\n"
            "color:black;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "QPushButton::hover{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(630, 220, 151, 32))
        self.pushButton_10.setStyleSheet(
            "QPushButton{\n"
            "color:white;\n"
            "background:#47545a;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "\n"
            "QPushButton::hover{\n"
            "color:#47545a;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.pushButton_10.setObjectName("pushButton_10")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 270, 761, 321))
        self.tableWidget.setStyleSheet(
            "background:white;\n" "border-radius:10px;\n" "padding:5px"
        )
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "APPLICATIONS"))
        self.lineEdit.setPlaceholderText(
            _translate("MainWindow", "Enter your search term...")
        )
        self.pushButton_2.setText(_translate("MainWindow", "Assigned Mentor Meetings"))
        self.pushButton_3.setText(_translate("MainWindow", "Unassigned Mentor Meetins"))
        self.pushButton_4.setText(_translate("MainWindow", "Previous VIT Control"))
        self.pushButton_5.setText(_translate("MainWindow", "Application Filtered"))
        self.pushButton_6.setText(_translate("MainWindow", "Duplicate Registration"))
        self.pushButton_7.setText(_translate("MainWindow", "Different Registration"))
        self.pushButton_8.setText(_translate("MainWindow", "All Aplications"))
        self.pushButton_9.setText(_translate("MainWindow", "Preferences"))
        self.pushButton_10.setText(_translate("MainWindow", "Exit"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Postcode"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Province"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Current Sit"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Economic Sit"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
