# Form implementation generated from reading ui file '/Users/yhtyyar/Documents/GitHub/Python-Module-Week7/mentor_menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("background-image: url(./assets/zemin-buyuk.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 240, 771, 341))
        self.tableWidget.setStyleSheet("QTableView{\n"
"color:black;\n"
"background:white;\n"
"font-weight:bold;\n"
"border-radius:5px\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.filter_select_button = QtWidgets.QComboBox(parent=self.centralwidget)
        self.filter_select_button.setGeometry(QtCore.QRect(340, 190, 441, 31))
        self.filter_select_button.setStyleSheet("QComboBox{\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"background:white;\n"
"color:black\n"
"}")
        self.filter_select_button.setObjectName("filter_select_button")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.filter_select_button.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 80, 291, 31))
        self.label.setStyleSheet("QLabel{\n"
"color:white;\n"
"font-size:36px;\n"
"font-weight:bold;\n"
"background:none\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.main_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.main_menu.setGeometry(QtCore.QRect(10, 190, 91, 31))
        self.main_menu.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.main_menu.setObjectName("main_menu")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(120, 190, 91, 31))
        self.exit_button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#47545a;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.all_meetings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.all_meetings.setGeometry(QtCore.QRect(10, 140, 201, 31))
        self.all_meetings.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.all_meetings.setObjectName("all_meetings")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 140, 351, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"padding:5px;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.search_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(700, 140, 75, 31))
        self.search_button.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.search_button.setObjectName("search_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filter_select_button.setItemText(0, _translate("MainWindow", "Vıt Projesinin Tamamına Katılması Uygun Olur"))
        self.filter_select_button.setItemText(1, _translate("MainWindow", "VIT Projesi ilk IT Eğtimi Al... ya Yönlendirilmesi Uygun Olur"))
        self.filter_select_button.setItemText(2, _translate("MainWindow", "VIT Projesi İngilizce Eğtimi Al... ya Yönlendirilmesi Uygun Olur"))
        self.filter_select_button.setItemText(3, _translate("MainWindow", "Vit Pojesi Kapsamında Dir.. Yönlendirilmesi Uygun Olur"))
        self.filter_select_button.setItemText(4, _translate("MainWindow", "Direkt Bireysel Koçluk İle İşe Yönlendirilmesi Uygun Olur"))
        self.filter_select_button.setItemText(5, _translate("MainWindow", "Bir Sonraki VIT Projesine Katılması Daha Uygun Olur"))
        self.filter_select_button.setItemText(6, _translate("MainWindow", "Başka Bir Sektöre Yönlendirilmesi"))
        self.filter_select_button.setItemText(7, _translate("MainWindow", "Diğer"))
        self.label.setText(_translate("MainWindow", "Mentor Interview"))
        self.main_menu.setText(_translate("MainWindow", "Main Menu"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.all_meetings.setText(_translate("MainWindow", "All Meetings"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your search term..."))
        self.search_button.setText(_translate("MainWindow", "Search"))
