# Form implementation generated from reading ui file '/Users/yhtyyar/Documents/GitHub/Python-Module-Week7/send_email_form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_send_email_form(object):
    def setupUi(self, send_email_form):
        send_email_form.setObjectName("send_email_form")
        send_email_form.resize(600, 400)
        send_email_form.setStyleSheet(
            "background-image: url(./assets/send_email.jpg);"
        )
        self.select_candidate = QtWidgets.QLabel(parent=send_email_form)
        self.select_candidate.setGeometry(QtCore.QRect(350, 40, 121, 16))
        self.select_candidate.setStyleSheet("font-weight:bold;\n" "background:none;")
        self.select_candidate.setObjectName("select_candidate")
        self.candidate_names = QtWidgets.QComboBox(parent=send_email_form)
        self.candidate_names.setGeometry(QtCore.QRect(350, 60, 221, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.candidate_names.setFont(font)
        self.candidate_names.setStyleSheet(
            "QComboBox{\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "background:white;\n"
            "color:black\n"
            "}"
        )
        self.candidate_names.setCurrentText("")
        self.candidate_names.setIconSize(QtCore.QSize(16, 16))
        self.candidate_names.setFrame(True)
        self.candidate_names.setObjectName("candidate_names")
        self.email = QtWidgets.QLineEdit(parent=send_email_form)
        self.email.setGeometry(QtCore.QRect(30, 60, 271, 31))
        self.email.setStyleSheet(
            "padding:5px;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "background:white;\n"
            "color:black\n"
            ""
        )
        self.email.setObjectName("email")
        self.label = QtWidgets.QLabel(parent=send_email_form)
        self.label.setGeometry(QtCore.QRect(30, 40, 101, 16))
        self.label.setStyleSheet("font-weight:bold;\n" "background:none;")
        self.label.setObjectName("label")
        self.subject_input = QtWidgets.QLineEdit(parent=send_email_form)
        self.subject_input.setGeometry(QtCore.QRect(32, 120, 541, 31))
        self.subject_input.setStyleSheet(
            "padding:5px;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "background:white;\n"
            "color:black\n"
            ""
        )
        self.subject_input.setObjectName("subject_input")
        self.label_2 = QtWidgets.QLabel(parent=send_email_form)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 61, 16))
        self.label_2.setStyleSheet("font-weight:bold;\n" "background:none;")
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(parent=send_email_form)
        self.textEdit.setGeometry(QtCore.QRect(30, 160, 541, 181))
        self.textEdit.setStyleSheet(
            "padding:5px;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "background:white;\n"
            "color:black\n"
            ""
        )
        self.textEdit.setObjectName("textEdit")
        self.send_button = QtWidgets.QPushButton(parent=send_email_form)
        self.send_button.setGeometry(QtCore.QRect(240, 350, 120, 32))
        self.send_button.setStyleSheet(
            "QPushButton{\n"
            "color:white;\n"
            "background:#db1e3c;\n"
            "border-radius:10px;\n"
            "font-weight:bold;\n"
            "}\n"
            "\n"
            "QPushButton::hover{\n"
            "color:#db1e3c;\n"
            "background:white;\n"
            "border-radius:10px;\n"
            "font-weight:bold\n"
            "}"
        )
        self.send_button.setObjectName("send_button")

        self.retranslateUi(send_email_form)
        QtCore.QMetaObject.connectSlotsByName(send_email_form)

    def retranslateUi(self, send_email_form):
        _translate = QtCore.QCoreApplication.translate
        send_email_form.setWindowTitle(_translate("send_email_form", "Send Email"))
        self.select_candidate.setText(_translate("send_email_form", "Candidates"))
        self.email.setPlaceholderText(
            _translate("send_email_form", "Enter a email address or populate...")
        )
        self.label.setText(_translate("send_email_form", "Email Address"))
        self.subject_input.setPlaceholderText(
            _translate("send_email_form", "Enter your email subject...")
        )
        self.label_2.setText(_translate("send_email_form", "Subject"))
        self.textEdit.setPlaceholderText(
            _translate("send_email_form", "Enter your message...")
        )
        self.send_button.setText(_translate("send_email_form", "Send"))
