# Form implementation generated from reading ui file '/Users/yhtyyar/Documents/GitHub/Python-Module-Week7/qt/interviews_menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("background-image: url(./assets/zemin-buyuk.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 60, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"font-size:36px;\n"
"font-weight:bold;\n"
"background:none")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(700, 180, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#47545a;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_gonderilmis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_gonderilmis.setGeometry(QtCore.QRect(290, 180, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_gonderilmis.setFont(font)
        self.pushButton_gonderilmis.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_gonderilmis.setObjectName("pushButton_gonderilmis")
        self.pushButton_ara = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ara.setGeometry(QtCore.QRect(700, 130, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_ara.setFont(font)
        self.pushButton_ara.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#db1e3c;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#db1e3c;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_ara.setObjectName("pushButton_ara")
        self.pushButton_gelmis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_gelmis.setGeometry(QtCore.QRect(20, 180, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_gelmis.setFont(font)
        self.pushButton_gelmis.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_gelmis.setObjectName("pushButton_gelmis")
        self.pushButton_tercih = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_tercih.setGeometry(QtCore.QRect(560, 180, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_tercih.setFont(font)
        self.pushButton_tercih.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_tercih.setObjectName("pushButton_tercih")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 130, 661, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-radius:10px;\n"
"background:none;\n"
"padding:5px\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 240, 761, 351))
        font = QtGui.QFont()
        font.setBold(True)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("\n"
"font-weight:bold;\n"
"background:none")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/arkaplan/WhatsApp Image 2024-10-17 at 23.49.08.jpeg\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "MULAKATLAR"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_gonderilmis.setText(_translate("MainWindow", "PROJESI GONDERILMIS OLANLAR"))
        self.pushButton_ara.setText(_translate("MainWindow", "ARA"))
        self.pushButton_gelmis.setText(_translate("MainWindow", "PROJESI GELMIS OLANLAR"))
        self.pushButton_tercih.setText(_translate("MainWindow", "TERCIHLER"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Aranacak bir metin girin..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ad -Soyad"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proje Gelis Tarihi"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", " Proje Gonderilis Tarihi"))
