# Form implementation generated from reading ui file '/Users/yhtyyar/Documents/GitHub/Python-Module-Week7/qt/user_menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("padding:0;\n"
"background-image: url(./assets/zemin-buyuk.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mulakatlar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mulakatlar.setGeometry(QtCore.QRect(320, 350, 141, 31))
        self.mulakatlar.setAutoFillBackground(False)
        self.mulakatlar.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.mulakatlar.setObjectName("mulakatlar")
        self.mentor_gorusmesi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mentor_gorusmesi.setGeometry(QtCore.QRect(520, 350, 181, 31))
        self.mentor_gorusmesi.setAutoFillBackground(False)
        self.mentor_gorusmesi.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.mentor_gorusmesi.setObjectName("mentor_gorusmesi")
        self.basvurular = QtWidgets.QPushButton(parent=self.centralwidget)
        self.basvurular.setGeometry(QtCore.QRect(100, 350, 141, 31))
        self.basvurular.setAutoFillBackground(False)
        self.basvurular.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.basvurular.setObjectName("basvurular")
        self.cikis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cikis.setGeometry(QtCore.QRect(610, 500, 91, 31))
        self.cikis.setAutoFillBackground(False)
        self.cikis.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#47545a;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.cikis.setObjectName("cikis")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 321, 41))
        self.label_2.setStyleSheet("color:white;\n"
"font-size:36px;\n"
"font-weight:bold;\n"
"background:none")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mulakatlar.setText(_translate("MainWindow", "MÜLAKATLAR"))
        self.mentor_gorusmesi.setText(_translate("MainWindow", "MENTÖR GÖRÜŞMESİ"))
        self.basvurular.setText(_translate("MainWindow", "BAŞVURULAR"))
        self.cikis.setText(_translate("MainWindow", "KAPAT"))
        self.label_2.setText(_translate("MainWindow", "TERCİHLER MENU"))
