# Form implementation generated from reading ui file 'C:\Git\Python_Modul_Week_2\Python_Modul_Week_2\pract-2\Python-Module-Week7\English\mentor_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-image: url(:/assets/assets/zemin-buyuk.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 240, 771, 341))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"color:black;\n"
"background:white;\n"
"font-weight:bold;\n"
"border-radius:5px\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 190, 441, 31))
        self.comboBox.setStyleSheet("QComboBox{\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"background:white;\n"
"color:black\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 80, 391, 31))
        self.label.setStyleSheet("QLabel{\n"
"color:white;\n"
"font-size:36px;\n"
"font-weight:bold;\n"
"background:none\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 190, 91, 31))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.all_interviews_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.all_interviews_Button.setGeometry(QtCore.QRect(10, 140, 201, 31))
        self.all_interviews_Button.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.all_interviews_Button.setObjectName("all_interviews_Button")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 140, 351, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"padding:5px;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 140, 75, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.usermenu_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.usermenu_Button.setGeometry(QtCore.QRect(120, 190, 151, 32))
        self.usermenu_Button.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.usermenu_Button.setObjectName("usermenu_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Interview_Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name_Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mentor"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IT_knowledge"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yeni Sütun"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Comments"))
        self.comboBox.setItemText(0, _translate("MainWindow", "It Would Be Appropriate to Participate in the Entire VIT Project"))
        self.comboBox.setItemText(1, _translate("MainWindow", "It Would Be Appropriate to Direct to the First IT Training in the VIT Project"))
        self.comboBox.setItemText(2, _translate("MainWindow", "It Would Be Appropriate to Direct to English Training in the VIT Project"))
        self.comboBox.setItemText(3, _translate("MainWindow", "It Would Be Appropriate to Direct Within the Scope of the VIT Project"))
        self.comboBox.setItemText(4, _translate("MainWindow", " It Would Be Appropriate to Direct to Employment with Individual Coaching"))
        self.comboBox.setItemText(5, _translate("MainWindow", "It Would Be More Appropriate to Participate in the Next VIT Project"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Directing to Another Sector"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Other"))
        self.label.setText(_translate("MainWindow", "MENTOR INTERVIEW"))
        self.pushButton_5.setText(_translate("MainWindow", "PREFERENCES"))
        self.all_interviews_Button.setText(_translate("MainWindow", "ALL INTERVIEWS"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter the Text to Search"))
        self.pushButton_2.setText(_translate("MainWindow", "SEARCH"))
        self.usermenu_Button.setText(_translate("MainWindow", "User Menu"))
