# Form implementation generated from reading ui file 'C:\Git\Python_Modul_Week_2\Python_Modul_Week_2\pract-2\Python-Module-Week7\English\user_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("padding:0;\n"
"background-image: url(:/assets/assets/zemin-buyuk.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.interviews_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.interviews_Button.setGeometry(QtCore.QRect(330, 290, 141, 31))
        self.interviews_Button.setAutoFillBackground(False)
        self.interviews_Button.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.interviews_Button.setObjectName("interviews_Button")
        self.mentor_interview_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mentor_interview_Button.setGeometry(QtCore.QRect(530, 290, 181, 31))
        self.mentor_interview_Button.setAutoFillBackground(False)
        self.mentor_interview_Button.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.mentor_interview_Button.setObjectName("mentor_interview_Button")
        self.app_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.app_Button.setGeometry(QtCore.QRect(110, 290, 141, 31))
        self.app_Button.setAutoFillBackground(False)
        self.app_Button.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.app_Button.setObjectName("app_Button")
        self.exit_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_Button.setGeometry(QtCore.QRect(620, 440, 91, 31))
        self.exit_Button.setAutoFillBackground(False)
        self.exit_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color:#47545a;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.exit_Button.setObjectName("exit_Button")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 110, 221, 41))
        self.label_2.setStyleSheet("color:white;\n"
"font-size:36px;\n"
"font-weight:bold;\n"
"background:none")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.interviews_Button.setText(_translate("MainWindow", "INTERVEIWS"))
        self.mentor_interview_Button.setText(_translate("MainWindow", "MENTOR INTERVIEW"))
        self.app_Button.setText(_translate("MainWindow", "APPLICATIONS"))
        self.exit_Button.setText(_translate("MainWindow", "EXİT"))
        self.label_2.setText(_translate("MainWindow", "USER MENU"))
